package com.alivc.player;

public interface IPlayingHandler {
    int MSG_OPEN_STATUS = 0;
    int MSG_LOAD_STATUS = 1;
    int MSG_PLAY_STATUS = 2;
    int MSG_PREPARE_STATUS = 3;
    int MSG_PLAY_PROGRESS = 4;
    int MSG_DECODE_STATUS = 5;
    int MSG_SIZE_STATUS = 6;
    int MSG_INFO_REPORT = 7;
    int MSG_FIRST_FRAME = 8;
    int MSG_PCM_DATA = 9;
    int MSG_CAPTURE_FRAME_DATA = 10;
    int MSG_SEI_DATA = 11;
    int MSG_DOWNLOAD_STATUS = 19;
    int MSG_NOT_AUTHED = 20;
    int MSG_BUFFER_UPDATE = 100;
    int k0Unknown = -1;
    int k0None = 0;
    int k0PrepareStart = 1;
    int k0PrepareFailed = 2;
    int k0Prepared = 3;
    int k0OpenStart = 4;
    int k0OpenFailed = 5;
    int k0Opened = 6;
    int k0LoadStart = 7;
    int k0LoadFailed = 8;
    int k0Loading = 9;
    int k0Loaded = 10;
    int k0PlayStarted = 11;
    int k0PlayPaused = 12;
    int k0PlayPausedForBuffering = 13;
    int k0PlayPausedForBufferingDone = 14;
    int k0PlayResumed = 15;
    int k0PlayStopped = 16;
    int k0PlaySeekDone = 17;
    int k0PlayEnd = 18;
    int k0DecodeDone = 19;
    int k0LoadingStart = 20;
    int k0LoadingEnd = 21;
    int k0LoadingProgress = 22;
    int k0LoadingTimeout = 23;
    int k0AudioDecoding = 24;
    int k0CircleStart = 25;
    int k1Unknow = -1;
    int k1None = 0;
    int k1NetworkError = 1;
    int k1FileOpenError = 2;
    int k1FileDemuxError = 3;
    int k1InvalidFile = 4;
    int k1AudioPlayed = 5;
    int k1VideoPlayed = 6;
    int k1NoInputFile = 7;
    int k1NoMemory = 8;
    int k1NoSupportCodec = 9;
    int k1NoVideo = 10;
    int k1NetworkTimeout = 11;
    int k1InvalidPswd = 12;
    int k1AudioDecodeFail = 13;
    int INFOREPORT_EMPTY = 0;
    int INFOREPORT_OPEN_PLAY = 1;
    int INFOREPORT_SEEK_START = 2;
    int INFOREPORT_SEEK_END = 3;
    int INFOREPORT_PAUSE_START = 4;
    int INFOREPORT_PAUSE_END = 5;
    int INFOREPORT_STOP = 6;
    int INFOREPORT_BUFFERING_START = 7;
    int INFOREPORT_BUFFERING_END = 8;
    int INFOREPORT_EOS = 9;
    int INFOREPORT_PLAYING_DOWN = 10;

    int onStatus(int var1, int var2, int var3, String var4);

    int onData(int var1, int var2, int var3, byte[] var4);
}
